export const eventsData  = [
  {
    title: "Yacht Party",
    description: "Get Ready for the Ultimate Yacht Party! Join us for an unforgettable night aboard a luxurious yacht. Dance the night away with electrifying beats from our top-tier DJs, and expect an incredible vibe!",
    date: "November 2, 2024",
    location: "Dubai, United Arab Emirates",
    link: "/ticketsCheckout",
    eventImage: '@/assets/img/hero/event-2.png',
  },
  {
    title: "Yacht Party",
    description: "Get Ready for the Ultimate Yacht Party! Join us for an unforgettable night aboard a luxurious yacht. Dance the night away with electrifying beats from our top-tier DJs, and expect an incredible vibe!",
    date: "November 9, 2024",
    location: "Dubai, United Arab Emirates",
    link: "/ticketsCheckout",
    eventImage: '@/assets/img/hero/event-2.png',
  },
  {
    title: "Yacht Party",
    description: "Get Ready for the Ultimate Yacht Party! Join us for an unforgettable night aboard a luxurious yacht. Dance the night away with electrifying beats from our top-tier DJs, and expect an incredible vibe!",
    date: "November 16, 2024",
    location: "Dubai, United Arab Emirates",
    link: "/ticketsCheckout",
    eventImage: '@/assets/img/hero/event-2.png',
  },
  {
    title: "Yacht Party",
    description: "Get Ready for the Ultimate Yacht Party! Join us for an unforgettable night aboard a luxurious yacht. Dance the night away with electrifying beats from our top-tier DJs, and expect an incredible vibe!",
    date: "November 23, 2024",
    location: "Dubai, United Arab Emirates",
    link: "/ticketsCheckout",
    eventImage: '@/assets/img/hero/event-2.png',
  },
  {
    title: "Yacht Party",
    description: "Get Ready for the Ultimate Yacht Party! Join us for an unforgettable night aboard a luxurious yacht. Dance the night away with electrifying beats from our top-tier DJs, and expect an incredible vibe!",
    date: "November 30, 2024",
    location: "Dubai, United Arab Emirates",
    link: "/ticketsCheckout",
    eventImage: '@/assets/img/hero/event-2.png',
  },
  {
    title: "Yacht Party",
    description: "Get Ready for the Ultimate Yacht Party! Join us for an unforgettable night aboard a luxurious yacht. Dance the night away with electrifying beats from our top-tier DJs, and expect an incredible vibe!",
    date: "December 07, 2024",
    location: "Dubai, United Arab Emirates",
    link: "/ticketsCheckout",
    eventImage: '@/assets/img/hero/event-2.png',
  },
  {
    title: "Yacht Party",
    description: "Get Ready for the Ultimate Yacht Party! Join us for an unforgettable night aboard a luxurious yacht. Dance the night away with electrifying beats from our top-tier DJs, and expect an incredible vibe!",
    date: "December 14, 2024",
    location: "Dubai, United Arab Emirates",
    link: "/ticketsCheckout",
    eventImage: '@/assets/img/hero/event-2.png',
  },
  {
    title: "Yacht Party",
    description: "Get Ready for the Ultimate Yacht Party! Join us for an unforgettable night aboard a luxurious yacht. Dance the night away with electrifying beats from our top-tier DJs, and expect an incredible vibe!",
    date: "December 21, 2024",
    location: "Dubai, United Arab Emirates",
    link: "/ticketsCheckout",
    eventImage: '@/assets/img/hero/event-2.png',
  },
  {
    title: "Yacht Party",
    description: "Get Ready for the Ultimate Yacht Party! Join us for an unforgettable night aboard a luxurious yacht. Dance the night away with electrifying beats from our top-tier DJs, and expect an incredible vibe!",
    date: "December 28, 2024",
    location: "Dubai, United Arab Emirates",
    link: "/ticketsCheckout",
    eventImage: '@/assets/img/hero/event-2.png',
  }
];
